### ISSUE TITLE
HTML 구조 만들기

### ISSUE THREAD

**Issue by HANKUGIN** [fluuuuuuu/css_prac4#2]

**Comment by HANKUGIN** [comment]
[Tiger Guid.txt](https://github.com/fluuuuuuu/css_prac4/files/11363898/Tiger.Guid.txt)

**Comment by fluuuuuuu** [comment]
<!DOCTYPE html>
<html lang='ko'>
    <head>
        <meta charset='UTF-8'>
        <title>Document</title>
    </head>
    <body>
        <div class="main">
            <div class="title">
                <span>호랑이</span>를 <span>주제</span>로 한 <span>민화</span>
            </div>
            <div class="mid">
                <div>
                    <ul>
                        <li>그림이 작가</li>
                        <li>그림의 시대</li>
                        <li>그림의 재료</li>
                        <li>그림의 주인공</li>
                        <li>그림의 활용</li>
                    </ul>
                </div>
                <div>
                    <div class="subtitle">승운용호도</div>
                    <div class="content">
                        사람 이름 같기도 한 이 그림을 처음 보았을 때 티셔츠에 새길 그림을 일러스트레이터로 작업 중이었다. 비록
						그림을 보며 원본대로 그려내는 작업이었지만 즐거웠다. 용과 겨루는 황금빛 호랑이의 모습이 용맹하기도 했지만 내게는 약간
						귀여워 보였고 무엇보다 순수해 보였다. 어둠 속에서 나타난 비겁한 용보다는 맑은 물을 튀며 신성한 기운을 드러내는 우리
						호랑이에서 무한한 애정을 느꼈기 때문이다.
                    </div>
                    <div class="subtitle">길상백호</div>
                    <div class="content">
                        호랑이 그림은 예로부터 아래로 내려오는 것보다 위로 올라가는 형상이 더 좋다고 하였다. 하지만 이 그림은
						달랐다. 아래로 내려오고 있기는 하지만 윤기나는 등의 털과 그윽하게 쳐다보는 두 눈은 백호의 여유로움을 충분히 공감할 수
						있게 해주었기 때문이다. 채도가 내려앉아 버린 백호의 그림이지만 건조해 보이기보다는 은빛으로 촉촉해 보이는 호랑이의
						자태에 반했다고 할까? 알록달록함이 주는 아기자기함은 없지만 세련된 무채색에 다부지게 밟아 짚은 앞발에서 오히려 나를
						지켜주는 든든함까지 느껴진다. 호랑이가 밟은 풀잎들에서도 우리를 한 공간 안에 무사히 존재하게 하는 안정감이 있는
						듯하다. 그림을 감상할 때 그 시대적 배경과 소재의 재질 등을 함께 감상하여 아는 즐거움을 늘려야 하겠지만 나는 아무
						부수적인 요소들을 제하고 오로지 내 눈과 그림이 서로 교감하여 빚어내는 상상의 공간을 좋아한다. 시대를 알고 의도를 아는
						것도 중요하겠지만 작가가 우리에게 오로지 늘 같은 그것만 바라지는 않았을 것 같다. 심지어 바랬다고 해도 그냥 미안하게
						생각하고 나만의 감상포인트를 놓치지 말아야겠다. 이것도 정체성을 잃지 않으려는 관객의 필사적인 노력으로 보아주기를
						바래본다.
                    </div>
                </div>
            </div>
            <div class="end">
                Copyright @ Allright Reserved.
            </div>
        </div>
    </body>
</html>

**Comment by fluuuuuuu** [comment]
/*

<!DOCTYPE html>
<html lang='ko'>
    <head>
        <meta charset='UTF-8'>
        <title>Document</title>
    </head>
    <body>
        <div class="main">
            <div class="title">
                <span>호랑이</span>를 <span>주제</span>로 한 <span>민화</span>
            </div>
            <div class="mid">
                <div>
                    <ul>
                        <li>그림이 작가</li>
                        <li>그림의 시대</li>
                        <li>그림의 재료</li>
                        <li>그림의 주인공</li>
                        <li>그림의 활용</li>
                    </ul>
                </div>
                <div>
                    <div class="subtitle">승운용호도</div>
                    <div class="content">
                        사람 이름 같기도 한 이 그림을 처음 보았을 때 티셔츠에 새길 그림을 일러스트레이터로 작업 중이었다. 비록
						그림을 보며 원본대로 그려내는 작업이었지만 즐거웠다. 용과 겨루는 황금빛 호랑이의 모습이 용맹하기도 했지만 내게는 약간
						귀여워 보였고 무엇보다 순수해 보였다. 어둠 속에서 나타난 비겁한 용보다는 맑은 물을 튀며 신성한 기운을 드러내는 우리
						호랑이에서 무한한 애정을 느꼈기 때문이다.
                    </div>
                    <div class="subtitle">길상백호</div>
                    <div class="content">
                        호랑이 그림은 예로부터 아래로 내려오는 것보다 위로 올라가는 형상이 더 좋다고 하였다. 하지만 이 그림은
						달랐다. 아래로 내려오고 있기는 하지만 윤기나는 등의 털과 그윽하게 쳐다보는 두 눈은 백호의 여유로움을 충분히 공감할 수
						있게 해주었기 때문이다. 채도가 내려앉아 버린 백호의 그림이지만 건조해 보이기보다는 은빛으로 촉촉해 보이는 호랑이의
						자태에 반했다고 할까? 알록달록함이 주는 아기자기함은 없지만 세련된 무채색에 다부지게 밟아 짚은 앞발에서 오히려 나를
						지켜주는 든든함까지 느껴진다. 호랑이가 밟은 풀잎들에서도 우리를 한 공간 안에 무사히 존재하게 하는 안정감이 있는
						듯하다. 그림을 감상할 때 그 시대적 배경과 소재의 재질 등을 함께 감상하여 아는 즐거움을 늘려야 하겠지만 나는 아무
						부수적인 요소들을 제하고 오로지 내 눈과 그림이 서로 교감하여 빚어내는 상상의 공간을 좋아한다. 시대를 알고 의도를 아는
						것도 중요하겠지만 작가가 우리에게 오로지 늘 같은 그것만 바라지는 않았을 것 같다. 심지어 바랬다고 해도 그냥 미안하게
						생각하고 나만의 감상포인트를 놓치지 말아야겠다. 이것도 정체성을 잃지 않으려는 관객의 필사적인 노력으로 보아주기를
						바래본다.
                    </div>
                </div>
            </div>
            <div class="end">
                Copyright @ Allright Reserved.
            </div>
        </div>
    </body>
</html>

*/

**Comment by fluuuuuuu** [comment]
[실습4 - 복사본.txt](https://github.com/fluuuuuuu/css_prac4/files/11363921/4.-.txt)

**Comment by HANKUGIN** [comment]
HTML 구조잡기

머지 완료했습니다.
